### ISSUE TITLE
Do czego służyć ma timestamp?

### ISSUE THREAD

**Issue by ApamNapat** [piotrekiiuwr/bd2019-projekt#11]
Jest argumentem wszystkich funkcji z wyjątkiem `open`, `trolls` i `leader`. Wiemy, że timestampy będą rosnąć, ale skoro mamy to zapewnione to nie musimy tego walidować. Więc co robić z tym argumentem?

**Comment by piotrekiiuwr** [comment]
`timestamp` jest potrzebny aby móc pozbawiać praw nieaktywnych członków partii.

**Comment by ApamNapat** [comment]
No oczywiście. Czy liderów też dotyczy w takim razie zamrażanie?
