### ISSUE TITLE
Dla projects ilość elementów krotki w opisie i specyfikacji wydaje się różna

### ISSUE THREAD

**Issue by ApamNapat** [piotrekiiuwr/bd2019-projekt#12]
###### projects

```
projects <timestamp> <member> <passwd> [ authority ]
```

Zwraca listę wszystkich działań ***1*** wraz z id organu ***2*** władzy prowadzącego dane działanie.
* Jeśli `<authority>` jest podane to zwraca wyłącznie akcje dotyczące działań danego `<authority>`
* `<passwd>` to hasło członka `<member>` będącego liderem.

Atrybuty zwracanych krotek, krotki muszą być posortowane wg `<project>` rosnąco

```
// <project> (1) <authority> (2) <actions> (3)
```
------
numeracja dodana przeze mnie. Czym tutaj miałoby być `actions`?

**Comment by piotrekiiuwr** [comment]
Fixed by a76241de665ff3936e14589
