### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by Tomatosoup97** [piotrekiiuwr/bd2019-projekt#15]
Czy rozwiązanie będzie sprawdzane pod kątem SQL Injection? Czy należy _escape_'ować znaki które dostajemy na wejściu?

teoria

**Comment by piotrekiiuwr** [comment]
Wywołania  będą zawsze w prawidłowym formacie, a wszystkie wartości będą odpowiedniego typu.
Nie można jednak wykluczyć, że jakiś [Little Bobby Tables dziwnie wyybierze  swoje hasło](https://xkcd.com/327/).  

> Identyfikatory <member>, <action>, <project>, <authority> są typu number i są globalnie unikalne (np. nie zdarzy się, że wartość <member> jest równa wartości <authority>)
> 
> Wartość <password> jest typu string, jej długość nie przekracza 128 znaków.
> 
> Wartość <timestamp> jest typu number i reprezentuje UNIX timestamp. Gwarantowane jest, że wszyskie wywołania będą podane na wejściu w kolejności rosnących timestampów.
