### ISSUE TITLE
Third-party apps

### ISSUE THREAD

**Issue by Tomatosoup97** [piotrekiiuwr/bd2019-projekt#16]
- Czy można użyć zewnętrznych zależności?
- Jak zainstalować zewnętrzne paczki? Czy można założyć, że dla Python'a będzie package-manager `pip`?

teoria

**Comment by piotrekiiuwr** [comment]
Używanie czegokolwiek należy uzgodnić ze prowadzącym ćwiczenia w swojej grupie.

Po uzyskaniu jego akceptacji wystarczy dołączyć do przesyłanego archiwum dokładne instrukcje instalacji i uruchomienia aplikacji (np. w postaci wywołań pip).
