### ISSUE TITLE
Obsługa --init

### ISSUE THREAD

**Issue by KoncepcyjnyMiliarder** [piotrekiiuwr/bd2019-projekt#18]
W jaki sposób oznaczony jest koniec informacji o liderach który otrzymujemy linia po linii podczas inicjalizacji, aby nie czekać w nieskończoność na wejście (kolejną linię)? Czy możemy założyć, że dane pochodzą z pliku, a więc wejściowy strumień się kończy?

teoria

**Comment by piotrekiiuwr** [comment]
tak
