### ISSUE TITLE
Dostęp do actions

### ISSUE THREAD

**Issue by lekcyjna123** [piotrekiiuwr/bd2019-projekt#19]
Mam pytanie co do specyfikacji funkcji `actions`. Według tego co jest napisane w projekt.md funkcję tą mogą wywoływać tylko liderzy. To oznacza że szeregowy członek partii nie jest wstanie sprawdzić jakie akcje są już prowadzone, i czy może po prostu zagłosować na już utworzoną akcje czy musi utworzyć nową. Analogicznie jeśli chce `zdownvotawać ` akcję jakiegoś trolla, to ma zadanie utrudnione, ponieważ nie wie jakie akcje istnieją. W związku z tym chciałbym się zapytać czy takie działanie funkcji `actions `jest zamierzone.
 
nic

**Comment by piotrekiiuwr** [comment]
Taki system sobie zaplanowali, trudno ;-)  Prawdopodobnie mają inne kanały komunikacji.
