### ISSUE TITLE
Co reprezentuje "authority"?

### ISSUE THREAD

**Issue by KoncepcyjnyMiliarder** [piotrekiiuwr/bd2019-projekt#20]
Z tekstu dokumentu można jedynie wywnioskować, że `<authority>` to jakaś bliżej nieokreślona liczba. Co ona dokładnie reprezentuje?

**Comment by piotrekiiuwr** [comment]
"authority" reprezentuje organ władzy, jeśli przygotuje Pani/Pan słownik pojęć to go włączę do projektu Mam wrażenie, że nie jest to jednak kluczowa kwestia.
