### ISSUE TITLE
Błąd w api "votes"

### ISSUE THREAD

**Issue by KoncepcyjnyMiliarder** [piotrekiiuwr/bd2019-projekt#22]
W opisie api votes widnieje:
"Zwraca listę wszystkich członków, **którzy oddawali głosy** wraz z sumarycznymi liczbami głosów za i przeciw."
Przykładowe wywołanie zwraca 3 krotki, lecz użytkownik numer 3 (dodany przy okazji pierwszego protestu) nie oddał żadnego głosu w żadnej akcji. Czy nie powinniśmy zatem zignorować go w zestawieniu?

**Comment by piotrekiiuwr** [comment]
Closed by 513f5659db7899e265bae99bf8b77975665206b0
