### ISSUE TITLE
Akcje authority

### ISSUE THREAD

**Issue by bratek20** [piotrekiiuwr/bd2019-projekt#24]
Authoriy podaje się przy pierwszej akcji dotyczącej danego projektu. Potem ten parametr jest pomijany. Pozwala to jednoznacznie związać authority z projektem. Czy działania authority to wszystkie akcję, przypisane do danego projektu czy tylko pierwsza akcja, która utworzyła projekt?

**Comment by piotrekiiuwr** [comment]
Działaniami authority są projekty, a nie akcje.
