### ISSUE TITLE
Trolls 

### ISSUE THREAD

**Issue by bratek20** [piotrekiiuwr/bd2019-projekt#25]
Czy zapytanie trolls bierze pod uwagę downvoty i upvoty zebrane przez wszystkie akcje danego członka czy każda akcja jest rozpatrywana osobno?

**Comment by piotrekiiuwr** [comment]
Chodzi o różnicę d - u, gdzie d to liczba downvotes dla wszystkich akcji danego członka, a u to liczba upvotes dla wszystkich akcji danego członka.
