### ISSUE TITLE
Czy to dalej prawda, że "Gwarantowane jest, że wszystkie wywołania będą podane na wejściu w kolejności rosnących timestampów."?

### ISSUE THREAD

**Issue by ApamNapat** [piotrekiiuwr/bd2019-projekt#28]
Skoro `trolls` dostaje argument `timestamp` to jaki ma on sens jeśli 

> Gwarantowane jest, że wszystkie wywołania będą podane na wejściu w kolejności rosnących timestampów.

Czyli jeśli obsługujemy wywołania API w kolejności, a inaczej chyba niekoniecznie jest sens to robić, to jaką dodatkową informację daje nam w tym wypadku `timestamp`, skoro jest on większy od `timestamp`ów wszystkich dotychczasowych głosów?

**Comment by ApamNapat** [comment]
Przy tym przykład 

```
{ "leader": { "timestamp": 1557475000, "password": "abc", "member": 1}}
{ "leader": { "timestamp": 1557474000. "password": "asd", "member": 2}}
```

nie spełnia powyższego wymogu

**Comment by KoncepcyjnyMiliarder** [comment]
Ja to widzę tak: timestamp był potrzebny aby mieć punkt odniesienia aby odliczyć rok w tył celem stwierdzenia, czy użytkownik jest jeszcze aktywny czy nie. Wywołanie `trolls` ze stampem sekunde po ostatniej akcji zwroci inny rezultat niz wywolanie np. 10 miesiecy po, moze okazać się, że w tym czasie ktoś stracił prawa członka.

**Comment by piotrekiiuwr** [comment]
@KoncepcyjnyMiliarder,  dzięki!
