### ISSUE TITLE
Potrzebne doprecyzowanie?

### ISSUE THREAD

**Issue by ApamNapat** [piotrekiiuwr/bd2019-projekt#29]
Jak mają się do siebie poniższe fragmenty:

> Można założyć, że wszystkie wywołania będą zawsze w prawidłowym formacie, a wszystkie wartości będą odpowiedniego typu.

> Status "ERROR"
> 
> Jeśli wywołanie funkcji nie odpowiada niniejszej specyfikacji należy zwrócić status "ERROR" (nie piszemy wariantów fail-safe itp.).

Jaką gwarancję daje nam fragment pierwszy a gwarancji czego nie mamy w świetle drugiego fragmentu?

**Comment by KoncepcyjnyMiliarder** [comment]
Ja zinterpretowałem to tak:
Fragment pierwszy - format wejścia to JSON, a linia którą otrzymamy będzie poprawnym obiektem i tego sprawdzać nie musimy. Dodatkowo jeśli oczekujemy zmiennej tekstowej, będzie ona tekstem, a liczba będzie liczbą, i tego również sprawdzać nie trzeba.

Fragment drugi - mimo to, możemy otrzymać obiekt niespełniający specyfikacji, na przykład dwa pola które się wykluczają w `actions`.
`actions <timestamp> <member> <password> [ <type> ] [ <project> | <authority> ] `
Jeśli project i authority są ustawione naraz, zgłaszamy błąd.

**Comment by piotrekiiuwr** [comment]
Jest tak jaki napisał KoncepcyjnyMiliarder:

> Fragment pierwszy - format wejścia to JSON, a linia którą otrzymamy będzie poprawnym obiektem i tego sprawdzać nie musimy. Dodatkowo jeśli oczekujemy zmiennej tekstowej, będzie ona tekstem, a liczba będzie liczbą, i tego również sprawdzać nie trzeba.


> Fragment drugi - mimo to, możemy otrzymać obiekt niespełniający specyfikacji, na przykład dwa pola które się wykluczają w `actions`.
> `actions <timestamp> <member> <password> [ <type> ] [ <project> | <authority> ] `
> Jeśli project i authority są ustawione naraz, zgłaszamy błąd.

Inny przykład:
- id nowego membera nie jest unikalne (np. występuje już jako id projektu).
