### ISSUE TITLE
Czy możemy założyć, że wszystkie wartości ID zmieszczą się w INT?

### ISSUE THREAD

**Issue by ApamNapat** [piotrekiiuwr/bd2019-projekt#30]
`Identyfikatory <member>, <action>, <project>, <authority> są typu number`  co rozumiem odnosi się do domeny JS(ON). Czy możemy je bezpiecznie pakować w POSTGRES'owe pole typu INT?

**Comment by piotrekiiuwr** [comment]
W tym projekcie można założyć, że nie zostanie przekroczony zakres typu `integer`.
Generalnie jeśli zakres nie jest podany to można zawsze użyć typu `numeric` 
WIęcej: https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-NUMERIC-DECIMAL
