### ISSUE TITLE
Brak wprost podanych konsekwencji błędnych wywołań/akcji

### ISSUE THREAD

**Issue by ApamNapat** [piotrekiiuwr/bd2019-projekt#8]
`...wpp <authority> musi być podana` Co jeśli nie będzie? Zwrócić ERROR czy nie dopuszczamy takiej możliwości?

`Można głosować co najwyżej jeden raz w sprawie każdej akcji` j.w. Co jeśli ktoś spróbuje zagłosować na to samo 2 razy?

teoria

**Comment by piotrekiiuwr** [comment]
Jeśli wejście nie odpowiada specyfikacji należy zwrócić status ERROR.
